services:
  - type: web
    name: rentit-backend
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: rentit-db
          property: connectionString
      - key: CLIENT_ORIGIN
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true

databases:
  - name: rentit-db
    databaseName: rentit
    user: postgres
    plan: free
